// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pealan/golang-rest-api/config"
	"github.com/pealan/golang-rest-api/handler"
	"github.com/pealan/golang-rest-api/repository"
	"github.com/pealan/golang-rest-api/router"
)

import (
	_ "github.com/pealan/golang-rest-api/docs"
)

// Injectors from wire.go:

func InitializeAPI() (*router.ServerHTTP, error) {
	db, err := config.ConnectToDB()
	if err != nil {
		return nil, err
	}
	deviceRepository := repository.DeviceRepositoryInit(db)
	deviceHandler := handler.DeviceHandlerInit(deviceRepository)
	serverHTTP := router.NewServerHTTP(deviceHandler)
	return serverHTTP, nil
}
